### ISSUE TITLE
Seismic prospecting giving incorrect oil field values 

### ISSUE THREAD

**Issue by Miisi** [SinTh0r4s/VisualProspecting#13]
tested on GTNH pre2.1.1.5 dev2, mod version `visualprospecting-1.7.10-latest-19-g9570f39.jar`

![image](https://user-images.githubusercontent.com/46682682/144066473-5fa7b66c-3703-445b-9a44-402c18f58d4c.png)
^contents shown by the detrav scanner

![image](https://user-images.githubusercontent.com/46682682/144066545-3658f79a-c2be-4113-818a-866d323ff846.png)
^same oil field after using a seismic prospector and analyzing the results

![image](https://user-images.githubusercontent.com/46682682/144066775-9c519e33-61a6-4568-a780-d0af31bd04ea.png)
^information given by the book. oil field [4] is the one shown in the images above

pumping from the field gives the fluid shown by the detrav scanner
removing the mod and analyzing the results from a seismic prospector gives the correct values
seems to affect all oil fields

**Comment by SinTh0r4s** [comment]
Thanks! There was an internal change in GT and I need to adapt to it. I am waiting for Glease to finalize it. Gonna be fixed rather soon!

**Comment by SinTh0r4s** [comment]
Could you verify if it is working for you? I don't have a world save for me. Please repeat all propecting steps for it. Beginning with the Advanced Seismic Prospector + TNT. Thanks!

https://github.com/SinTh0r4s/VisualProspecting/releases/tag/1.0.21b

**Comment by Miisi** [comment]
getting this error in GregTech.log after attempting to right-click an advanced seismic prospector, after putting explosives in, with a data stick 

```
Encountered Exception while rightclicking TileEntity, the Game should've crashed now, but I prevented that. Please report immediately to GregTech Intergalactical!!!
java.lang.NoSuchMethodError: gregtech.common.GT_UndergroundOil.undergroundOil(Lnet/minecraft/world/World;IIF)Lnet/minecraftforge/fluids/FluidStack;
	at com.sinthoras.visualprospecting.database.ServerCache.prospectUndergroundFluidBlockRadius(ServerCache.java:83)
	at gregtech.common.tileentities.machines.basic.GT_MetaTileEntity_AdvSeismicProspector.onRightclick(GT_MetaTileEntity_AdvSeismicProspector.java:578)
	at gregtech.api.metatileentity.MetaTileEntity.onRightclick(MetaTileEntity.java:251)
	at gregtech.api.metatileentity.BaseMetaTileEntity.onRightclick(BaseMetaTileEntity.java:1621)
	at gregtech.common.blocks.GT_Block_Machines.func_149727_a(GT_Block_Machines.java:361)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at fastcraft.at.a(F:978)
	at fastcraft.H.aq(F:36)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by SinTh0r4s** [comment]
Darn! You need to update GT as well: http://jenkins.usrv.eu:8080/job/Gregtech-5-Unofficial/lastSuccessfulBuild/artifact/build/libs/gregtech-5.09.40.00.jar

**Comment by Miisi** [comment]
oops. seems to be working fine now, thanks!

**Comment by SinTh0r4s** [comment]
Awesome! Thank you very much for testing it out.
